# Generated by Django 3.0 on 2020-01-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2500)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dislike',
                'verbose_name_plural': 'Dislikes',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=2300, null=True)),
                ('category', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incentive',
                'verbose_name_plural': 'Incentives',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=50)),
                ('professional', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('institution_name', models.CharField(blank=True, max_length=50)),
                ('profile_photo', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('update_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2500)),
                ('due_date', models.DateField()),
                ('sector', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_discoverable', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2500)),
                ('file', models.CharField(max_length=500)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Goal')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
            },
        ),
        migrations.CreateModel(
            name='RequirementArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=50)),
                ('artifact_content', models.CharField(max_length=500)),
                ('artifact_link', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_file', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Requirement')),
            ],
            options={
                'verbose_name': 'RequirementArtifact',
                'verbose_name_plural': 'RequirementArtifacts',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1500)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Requirement')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
            },
        ),
        migrations.CreateModel(
            name='StarRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stars', models.IntegerField()),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
            ],
            options={
                'verbose_name': 'StarRate',
                'verbose_name_plural': 'StarRates',
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usecase_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('file', models.CharField(max_length=500)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Process')),
            ],
            options={
                'verbose_name': 'UseCase',
                'verbose_name_plural': 'UseCases',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Viewpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewpoint_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2300)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Viewpoint',
                'verbose_name_plural': 'Viewpoints',
            },
        ),
        migrations.CreateModel(
            name='ViewPointRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
                ('view_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Viewpoint')),
            ],
            options={
                'verbose_name': 'ViewPointRate',
                'verbose_name_plural': 'ViewPointRates',
            },
        ),
        migrations.CreateModel(
            name='ViewpointLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
                ('view_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Viewpoint')),
            ],
            options={
                'verbose_name': 'ViewpointLike',
                'verbose_name_plural': 'ViewpointLikes',
            },
        ),
        migrations.CreateModel(
            name='ViewpointDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('view_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Viewpoint')),
            ],
            options={
                'verbose_name': 'ViewpointDislike',
                'verbose_name_plural': 'ViewpointDislikes',
            },
        ),
        migrations.CreateModel(
            name='ViewPointComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Viewpoint')),
            ],
            options={
                'verbose_name': 'ViewPointComment',
                'verbose_name_plural': 'ViewPointComments',
            },
        ),
        migrations.CreateModel(
            name='UseCaseRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
                ('usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UseCase')),
            ],
            options={
                'verbose_name': 'UseCaseRate',
                'verbose_name_plural': 'UseCaseRates',
            },
        ),
        migrations.CreateModel(
            name='UseCaseLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UseCase')),
            ],
            options={
                'verbose_name': 'UseCaseLike',
                'verbose_name_plural': 'UseCaseLikes',
            },
        ),
        migrations.CreateModel(
            name='UseCaseDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UseCase')),
            ],
            options={
                'verbose_name': 'UseCaseDislike',
                'verbose_name_plural': 'UseCaseDislikes',
            },
        ),
        migrations.CreateModel(
            name='UseCaseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UseCase')),
            ],
            options={
                'verbose_name': 'UseCaseComment',
                'verbose_name_plural': 'UseCaseComments',
            },
        ),
        migrations.CreateModel(
            name='ScenarioRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Scenario')),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
            ],
            options={
                'verbose_name': 'ScenarioRate',
                'verbose_name_plural': 'ScenarioRates',
            },
        ),
        migrations.CreateModel(
            name='ScenarioLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Scenario')),
            ],
            options={
                'verbose_name': 'ScenarioLike',
                'verbose_name_plural': 'ScenarioLikes',
            },
        ),
        migrations.CreateModel(
            name='ScenarioDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Scenario')),
            ],
            options={
                'verbose_name': 'ScenarioDislike',
                'verbose_name_plural': 'ScenarioDislikes',
            },
        ),
        migrations.CreateModel(
            name='ScenarioComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Scenario')),
            ],
            options={
                'verbose_name': 'ScenarioComment',
                'verbose_name_plural': 'ScenarioComments',
            },
        ),
        migrations.CreateModel(
            name='RequiremetDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Requirement')),
            ],
            options={
                'verbose_name': 'RequiremetDislike',
                'verbose_name_plural': 'RequiremetDislikes',
            },
        ),
        migrations.CreateModel(
            name='RequirementRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Requirement')),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
            ],
            options={
                'verbose_name': 'RequirementRate',
                'verbose_name_plural': 'RequirementRates',
            },
        ),
        migrations.CreateModel(
            name='RequirementLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Requirement')),
            ],
            options={
                'verbose_name': 'RequirementLike',
                'verbose_name_plural': 'RequirementLikes',
            },
        ),
        migrations.CreateModel(
            name='RequirementComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Requirement')),
            ],
            options={
                'verbose_name': 'RequirementComment',
                'verbose_name_plural': 'RequirementComments',
            },
        ),
        migrations.CreateModel(
            name='RequirementArtifactRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('requiremet_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.RequirementArtifact')),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
            ],
            options={
                'verbose_name': 'RequirementArtifactRate',
                'verbose_name_plural': 'RequirementArtifactRates',
            },
        ),
        migrations.CreateModel(
            name='RequirementArtifactLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
                ('requirement_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.RequirementArtifact')),
            ],
            options={
                'verbose_name': 'RequirementArtifactLike',
                'verbose_name_plural': 'RequirementArtifactLikes',
            },
        ),
        migrations.CreateModel(
            name='RequirementArtifactDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('requirement_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.RequirementArtifact')),
            ],
            options={
                'verbose_name': 'RequirementArtifactDislike',
                'verbose_name_plural': 'RequirementArtifactDislikes',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=500)),
                ('resource_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositorys',
            },
        ),
        migrations.CreateModel(
            name='ProjectRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
            ],
            options={
                'verbose_name': 'ProjectRate',
                'verbose_name_plural': 'ProjectRates',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'ProjectMembership',
                'verbose_name_plural': 'ProjectMemberships',
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'ProjectLike',
                'verbose_name_plural': 'ProjectLikes',
            },
        ),
        migrations.CreateModel(
            name='ProjectIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Incentive')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'ProjectIncentive',
                'verbose_name_plural': 'ProjectIncentives',
            },
        ),
        migrations.CreateModel(
            name='ProjectDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'ProjectDislike',
                'verbose_name_plural': 'ProjectDislikes',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'ProjectComment',
                'verbose_name_plural': 'ProjectComments',
            },
        ),
        migrations.CreateModel(
            name='ProcessRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Process')),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
            ],
            options={
                'verbose_name': 'ProcessRate',
                'verbose_name_plural': 'ProcessRates',
            },
        ),
        migrations.CreateModel(
            name='ProcessLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Process')),
            ],
            options={
                'verbose_name': 'ProcessLike',
                'verbose_name_plural': 'ProcessLikes',
            },
        ),
        migrations.CreateModel(
            name='ProcessDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Process')),
            ],
            options={
                'verbose_name': 'ProcessDislike',
                'verbose_name_plural': 'ProcessDislikes',
            },
        ),
        migrations.CreateModel(
            name='ProcessComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Process')),
            ],
            options={
                'verbose_name': 'ProcessComment',
                'verbose_name_plural': 'ProcessComments',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Scenario'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.User'),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.User')),
            ],
            options={
                'verbose_name': 'LoginLog',
                'verbose_name_plural': 'LoginLogs',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member'),
        ),
        migrations.CreateModel(
            name='GoalRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Goal')),
                ('star_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StarRate')),
            ],
            options={
                'verbose_name': 'GoalRate',
                'verbose_name_plural': 'GoalRates',
            },
        ),
        migrations.CreateModel(
            name='GoalLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Goal')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
            ],
            options={
                'verbose_name': 'GoalLike',
                'verbose_name_plural': 'GoalLikes',
            },
        ),
        migrations.CreateModel(
            name='GoalDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Goal')),
            ],
            options={
                'verbose_name': 'GoalDislike',
                'verbose_name_plural': 'GoalDislikes',
            },
        ),
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Goal')),
            ],
            options={
                'verbose_name': 'GoalComment',
                'verbose_name_plural': 'GoalComments',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member'),
        ),
        migrations.AddField(
            model_name='goal',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Viewpoint'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='disliked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Like')),
            ],
            options={
                'verbose_name': 'CommentLike',
                'verbose_name_plural': 'CommentLikes',
            },
        ),
        migrations.CreateModel(
            name='CommentDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Dislike')),
            ],
            options={
                'verbose_name': 'CommentDislike',
                'verbose_name_plural': 'CommentDislikes',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member'),
        ),
        migrations.CreateModel(
            name='ArtifactComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Comment')),
                ('requirement_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.RequirementArtifact')),
            ],
            options={
                'verbose_name': 'ArtifactComment',
                'verbose_name_plural': 'ArtifactComments',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500)),
                ('activity_time', models.DateTimeField()),
                ('created_on', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.User')),
            ],
            options={
                'verbose_name': 'ActivityLog',
                'verbose_name_plural': 'ActivityLogs',
            },
        ),
    ]
