# Generated by Django 3.0.6 on 2020-06-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmemberincentive',
            old_name='projectincetive',
            new_name='projectincentive',
        ),
    ]
