# Generated by Django 3.0.5 on 2020-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='file',
            new_name='usecase_link',
        ),
        migrations.RemoveField(
            model_name='process',
            name='file',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_docs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='process_docs',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='process',
            name='process_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='process_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_docs',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_docs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usecase',
            name='usecase_docs',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usecase',
            name='usecase_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='requirementartifact',
            name='uploaded_file',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='viewpoint_docs',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='viewpoint_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
