# Generated by Django 3.0 on 2020-01-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200123_0718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequiremetDislike',
            new_name='RequirementDislike',
        ),
    ]
