# Generated by Django 3.1b1 on 2020-06-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200617_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(default='user.png', max_length=50, upload_to=''),
        ),
    ]
