# Generated by Django 3.0.5 on 2020-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200424_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_files',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
