# Generated by Django 3.1b1 on 2020-06-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200618_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultViewpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewpoint_name', models.CharField(max_length=500)),
                ('viewpoint_photo', models.ImageField(default='logo.png', max_length=50, upload_to='')),
                ('description', models.TextField(max_length=5000)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DefailtViewpoint',
                'verbose_name_plural': 'DefailtViewpoints',
            },
        ),
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_docs',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_link',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_photo',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_docs',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_links',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_photo',
        ),
        migrations.RemoveField(
            model_name='process',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_docs',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_links',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_photo',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='process',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='usecase_docs',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='usecase_link',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='usecase_photo',
        ),
        migrations.AddField(
            model_name='process',
            name='requirement',
            field=models.ManyToManyField(blank=True, to='projects.Requirement'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='requirement',
            field=models.ManyToManyField(to='projects.Requirement'),
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='requirement',
        ),
        migrations.AddField(
            model_name='scenario',
            name='requirement',
            field=models.ManyToManyField(blank=True, to='projects.Requirement'),
        ),
    ]
