# Generated by Django 3.0.5 on 2020-04-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200428_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
