# Generated by Django 3.1b1 on 2020-06-19 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200619_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementscenario',
            name='requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.requirement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirementscenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.scenario'),
        ),
    ]
