# Generated by Django 3.0.2 on 2020-04-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200416_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sectors',
            new_name='Sector',
        ),
    ]
