# Generated by Django 3.1b1 on 2020-06-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200619_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='requirement_docs',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='requirement_links',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='requirement_photo',
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='viewpoint',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
