# Generated by Django 3.1b1 on 2020-06-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200621_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='status',
            field=models.CharField(default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='status',
            field=models.CharField(default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='status',
            field=models.CharField(default='pending', max_length=60),
        ),
    ]
