# Generated by Django 3.0.5 on 2020-04-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_goal_goal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
