# Generated by Django 3.0.2 on 2020-04-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_member_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
