# Generated by Django 3.0.5 on 2020-04-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200429_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='file',
            new_name='requirement_links',
        ),
    ]
