# Generated by Django 3.0.2 on 2020-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200417_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
