# Generated by Django 3.1b1 on 2020-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200625_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifactcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goalcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requirementcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scenariocomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usecasecomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='viewpointcomment',
            options={},
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='logout_time',
            field=models.DateTimeField(),
        ),
    ]
