# Generated by Django 3.0.2 on 2020-04-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200417_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_files',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='viewpoint_docs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='viewpoint_links',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='viewpoint_photo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
