# Generated by Django 3.0.5 on 2020-04-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200429_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
