# Generated by Django 3.1b1 on 2020-06-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200628_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='created_on',
        ),
    ]
