# Generated by Django 3.0.5 on 2020-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200429_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='scenario_links',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
