# Generated by Django 3.1b1 on 2020-06-28 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_loginlog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
