# Generated by Django 3.0.5 on 2020-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200430_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_links',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
