# Generated by Django 3.1b1 on 2020-06-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_visitors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visitor',
        ),
    ]
