# Generated by Django 3.0.5 on 2020-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_process_process_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, default='Tanzania', max_length=50),
        ),
    ]
