# Generated by Django 3.1b1 on 2020-07-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200628_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ViewpointGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.goal')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.viewpoint')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.goal')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='GoalRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_goal', models.IntegerField(max_length=20)),
                ('relation_type', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('origin_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.goal')),
            ],
        ),
        migrations.CreateModel(
            name='GoalDecomposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decomposed_goal', models.IntegerField(max_length=20)),
                ('decomposition_type', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('original_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.goal')),
            ],
        ),
    ]
