# Generated by Django 3.0.5 on 2020-05-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_starrate_rate_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starrate',
            options={},
        ),
        migrations.RemoveField(
            model_name='starrate',
            name='rate_status',
        ),
    ]
