# Generated by Django 3.1b1 on 2020-07-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200704_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalrelationship',
            name='related_goal',
            field=models.IntegerField(),
        ),
    ]
