# Generated by Django 3.0.5 on 2020-05-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200504_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrate',
            options={},
        ),
    ]
