# Generated by Django 3.1b1 on 2020-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200705_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaldecomposition',
            name='decomposed_goal',
            field=models.IntegerField(),
        ),
    ]
