# Generated by Django 3.0.6 on 2020-05-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200506_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='project',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='resource_name',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='repository',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='repository',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='repository',
            name='links',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
