# Generated by Django 3.1b1 on 2020-07-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200705_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goaldecomposition',
            old_name='decomposition_type',
            new_name='decomposition_operator',
        ),
    ]
