# Generated by Django 3.0.6 on 2020-05-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20200508_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewpointRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Repository')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Viewpoint')),
            ],
        ),
    ]
