# Generated by Django 3.0.6 on 2020-05-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_viewpointrepository'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Repository')),
            ],
        ),
    ]
