# Generated by Django 3.1b1 on 2020-07-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20200708_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewpointdislike',
            old_name='view_point',
            new_name='viewpoint',
        ),
    ]
