# Generated by Django 3.0.6 on 2020-05-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentive',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectincentive',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='projectincentive',
            name='unit',
        ),
        migrations.AddField(
            model_name='projectincentive',
            name='description',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectincentive',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Member'),
            preserve_default=False,
        ),
    ]
