# Generated by Django 3.1b1 on 2020-07-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20200712_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewpointlike',
            old_name='view_point',
            new_name='viewpoint',
        ),
        migrations.RenameField(
            model_name='viewpointrate',
            old_name='view_point',
            new_name='view_oint',
        ),
    ]
