# Generated by Django 3.1b1 on 2020-07-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20200712_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewpointrate',
            old_name='view_oint',
            new_name='viewpoint',
        ),
    ]
