# Generated by Django 3.0.6 on 2020-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_goalrepository_processrepository_requirementrepository_scenariorepository_usecaserepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectincentive',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='viewpoint',
            name='viewpoint_name',
            field=models.CharField(max_length=500),
        ),
    ]
