# Generated by Django 3.0.8 on 2020-07-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_projectincentive_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectincentive',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
