version: "3"

services:
  # pgadmin:
  #   restart: "always"
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - 8001:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: daniellykindimba@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: imis%100
  #   depends_on:
  #     - db
  db:
    restart: "always"
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Namwinyu1995
      POSTGRES_USER: postgres
      POSTGRES_DB: cores
    ports:
      - "6543:5432"
    # volumes:
    #   - /var/lib/postgresql/12/main:/var/lib/postgresql/data
  # redis:
  #   restart: "always"
  #   image: redis:latest
  web:
    restart: "always"
    build: .
    # environment:
    #   IP: 41.59.88.233
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: core
    image: core
    working_dir: /core
    # volumes:
    #   - .:/core
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis

